
language: node_js
env:
  - CODECOV_TOKEN=ada463b3-52b8-4d7a-a257-749e01836bec
node_js:
  - 'stable'
before_script:
  - psql -c 'create database joao_jose_api_test;' -U postgres
script:
  - yarn lint
  - yarn build
  - yarn report-coverage
  - yarn test
after_success:
  - curl -s https://codecov.io/bash | bash
services: 
  - postgresql